name: Flask App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-flask-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # or match your local version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask app (test mode)
        env:
          FLASK_APP: app.py  # change if your entry is different
          FLASK_ENV: development
        run: |
          python -m flask run &
          sleep 10  # wait for Flask server to start
          curl --fail http://127.0.0.1:5000  # check if homepage loads

      - name: Check model load (optional)
        run: |
          python -c "import pickle; open('model.pkl', 'rb')" || echo "Model not found or invalid"
