name: Flask App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # or your local version

      - name: Install dependencies (force scikit-learn==1.6.1)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install scikit-learn==1.6.1

      - name: Run Flask App Test
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
        run: |
          python -m flask run &
          sleep 10
          curl --fail http://127.0.0.1:5000

      - name: Confirm model loads
        run: |
          python -c "import pickle; pickle.load(open('model.pkl', 'rb'))"
